In [1]:
import pandas as pd

In [3]:
input=pd.read_csv('C:\\Users\\admin\\Desktop\\iot\\input_signal_data.csv')

In [4]:
input

,polar2,azimuth2,x2,y2,z2,polar1,azimuth1,x1,y1,z1
0,6.000000,41.341361,0.078479,0.069046,0.994522,0.0,0.0,0.000000,0.000000e+00,1.0
1,6.054054,10.499738,0.103701,0.019219,0.994423,0.0,0.0,0.000000,0.000000e+00,1.0
2,6.108108,13.327770,0.103539,0.024529,0.994323,0.0,0.0,0.000000,0.000000e+00,1.0
3,6.162162,35.111162,0.087810,0.061740,0.994222,0.0,0.0,0.000000,0.000000e+00,1.0
4,6.216216,64.446891,0.046707,0.097689,0.994120,0.0,0.0,0.000000,0.000000e+00,1.0
...,...,...,...,...,...,...,...,...,...,...
1189995,60.530283,70.047866,0.297085,0.818360,0.491963,60.0,360.0,0.866025,-2.121150e-16,0.5
1189996,51.842044,73.488695,0.223473,0.753886,0.617832,60.0,360.0,0.866025,-2.121150e-16,0.5
1189997,40.139778,77.651256,0.137867,0.629740,0.764474,60.0,360.0,0.866025,-2.121150e-16,0.5
1189998,57.862016,71.322796,0.271166,0.802177,0.531960,60.0,360.0,0.866025,-2.121150e-16,0.5
1189999,99.762030,46.751449,0.675244,0.717842,-0.169556,60.0,360.0,0.866025,-2.121150e-16,0.5

In [7]:
input_columns

               x2        y2        z2        x1            y1   z1
0        0.078479  0.069046  0.994522  0.000000  0.000000e+00  1.0
1        0.103701  0.019219  0.994423  0.000000  0.000000e+00  1.0
2        0.103539  0.024529  0.994323  0.000000  0.000000e+00  1.0
3        0.087810  0.061740  0.994222  0.000000  0.000000e+00  1.0
4        0.046707  0.097689  0.994120  0.000000  0.000000e+00  1.0
...           ...       ...       ...       ...           ...  ...
1189995  0.297085  0.818360  0.491963  0.866025 -2.121150e-16  0.5
1189996  0.223473  0.753886  0.617832  0.866025 -2.121150e-16  0.5
1189997  0.137867  0.629740  0.764474  0.866025 -2.121150e-16  0.5
1189998  0.271166  0.802177  0.531960  0.866025 -2.121150e-16  0.5
1189999  0.675244  0.717842 -0.169556  0.866025 -2.121150e-16  0.5

[1190000 rows x 6 columns]

In [ ]:
class LSTMModel(nn.Module):
    def __init__(self,input_size,hidden_size,num_layers,output_size):
        super(LSTMModel,self).__init__()
        self.lstm=nn.LSTM(input_size,hidden_size,num_layers,batch_first=True)
        self.linear1=nn.Linear(hidden_size,hidden_size/2)
        self.linear2=nn.Linear(hidden_size/2,output_size)
        self.linear3=nn.Linear(128,128)
    
    def forward(self,x):
        h0=torch.zeros(self.lstm.num_layers,x.size(0),self.lstm.hidden_size).to(device)
        c0=torch.zeros(self.lstm.num_layers,x.size(0),self.lstm.hidden_size).to(device)

        out,_=self.lstm(x,(h0,c0))
        out=out[:,-1,:]
        out=F.tanh(self.linear1(out))
        out=F.sigmoid(self.linear2(out))
        out=self.linear3(out)

        return out